import ProfileImg from '../assets/images/dummy_image.png';

const dummy_data = [
  {
    id: 1,
    name: '이민구',
    content: '점심 먹었니 친구야?',
    created_date: '12:03PM',
    position: 'left',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 2,
    name: '나',
    content: '아니 아직 안먹었어, 너는 먹었니?',
    created_date: '12:03PM',
    position: 'right',
    profileImgUlr: ProfileImg,
    isOpen: true,
  },
  {
    id: 3,
    name: '나',
    content: '안먹었으면 같이 먹을까?? 먹고싶은 메뉴가 있으면 말해보겠니?',
    created_date: '12:03PM',
    position: 'right',
    profileImgUlr: ProfileImg,
    isOpen: true,
  },
  {
    id: 4,
    name: '이민구',
    content:
      '나는 풍자 또 간집에 나온 소라 편의점의 제육볶음이 너무 먹고싶구나ㅎㅎㅎㅎ',
    created_date: '12:03PM',
    position: 'left',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 5,
    name: '나',
    content: '그럼먹으러 가자구~~',
    created_date: '12:03PM',
    position: 'right',
    profileImgUlr: ProfileImg,
    isOpen: true,
  },
  {
    id: 6,
    name: '이민구',
    content: '오 몇시에 만날래?',
    created_date: '12:04PM',
    position: 'left',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 7,
    name: '나',
    content: '아 점심은 안되고 저녁에 먹을까?',
    created_date: '12:07PM',
    position: 'right',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 8,
    name: '이민구',
    content: '오 몇시에 만날래?',
    created_date: '12:04PM',
    position: 'left',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 9,
    name: '나',
    content: '아 점심은 안되고 저녁에 먹을까?',
    created_date: '12:07PM',
    position: 'right',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 10,
    name: '이민구',
    content: '오 몇시에 만날래?',
    created_date: '12:04PM',
    position: 'left',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
  {
    id: 11,
    name: '나',
    content: '아 점심은 안되고 저녁에 먹을까?',
    created_date: '12:07PM',
    position: 'right',
    profileImgUrl: ProfileImg,
    isOpen: true,
  },
];

export default dummy_data;
